services:
  database:
    image: postgres:latest
    container_name: next-starter-database
    environment:
      POSTGRES_DB: next-starter
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    # volumes:
    #   - ./.docker/postgres:/var/lib/postgresql/data

  prisma-studio:
    image: timothyjmiller/prisma-studio
    container_name: next-starter-prisma-studio
    depends_on:
      - database
    restart: always
    ports:
      - 5555:5555
    environment:
      POSTGRES_URL: postgresql://docker:docker@database:5432/next-starter

  stripe-webhook:
    image: stripe/stripe-cli:latest
    container_name: next-starter-stripe-webhook
    command: listen --forward-to http://host.docker.internal:3000/api/auth/stripe/webhook
    env_file:
      - .env
    depends_on:
      - database
